@startuml business
skinparam classAttributeIconSize 0

' ===== LUT =====
entity "Look Up Table" as LUT {
  - id: Long
  - name: String
  - type: String
  - is_active: Boolean = true
}

' ===== Work Details =====
class WorkDetails {
  - work_model: LUT
  - employment_type: LUT
  - job_title: LUT
  - schedule: JSON
  - is_active: Boolean
  - branch: Branch
  - user: User
}

' ===== Company =====
entity Company {
  - id: Long
  - name: String
}

' ===== Branch =====
entity Branch {
  - id: Long
  - name: String
  - registration_number: String {length = 14}
  - is_matriz: Boolean = false
  - is_active: Boolean = true
  - company: Company
}

' ===== User Details =====
entity UserDetails {
  - id: Long
  - name: String
  - last_name: String
  - identification_number: Long {length = 11}
  - user_type: LUT
  - user: User
}

' ===== User =====
entity User {
  - id: Long
  - email: String
  - password: String
  - is_superuser: Boolean = false
  - is_first_access: Boolean = true
  - is_active: Boolean = true
}

' ===== Work Log =====
entity WorkLog {
  - id: Long
  - sequential_registration_number: Long {length = 9}
  - datetime: Timestamp
  - fiscal_date: String {length = 8}
  - fiscal_time: String {length = 4}
  - geolocation: Point
  - status: LUT = "OK"
  - hash: String {length = 64}
  - user: User
}

' ===== Work Log Adjustment =====
entity WorkLogAdjustment {
  - id: Long
  - datetime: Timestamp
  - requested_at: Date
  - status: LUT = "PENDING"
  - rejection_reason: String
  - work_log: WorkLog
  - authorized_by: User
}

' ===== Notification =====
entity Notification {
  - id: Long
  - text: String
  - title: LUT
  - status: LUT = "UNREAD"
  - user: User
}

' ===== Relationships =====

' LookUpTable LUT
LUT "1" o-- "many" WorkDetails
LUT "1" o-- "many" UserDetails
LUT "1" o-- "many" WorkLog
LUT "1" o-- "many" WorkLogAdjustment
LUT "1" o-- "many" Notification

' Company
Company "1" *-- "many" Branch

' UserDetails
UserDetails "1" --* "1" User
UserDetails "1" --> "many" Branch

' Notification
Notification "many" --* "1" User

' WorkDetails
WorkDetails "1" --o "1" Branch
WorkDetails "1" --* "1" User

' WorkLog
User "1" *-- "many" WorkLog
WorkLog "0.1" *-- "many" WorkLogAdjustment

' WorkLogAdjustment
WorkLogAdjustment "many" --o "1" User
@enduml
