spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME}
